# Generated by Django 5.1.2 on 2024-12-03 01:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('user_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('post_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('post_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('post_description', models.TextField(blank=True, null=True)),
                ('post_title', models.CharField(max_length=200)),
                ('visible_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Email'), ('phone_number', 'Phone Number'), ('address', 'Address')], max_length=30), size=None)),
                ('post_type', models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
