# Generated by Django 5.1.2 on 2024-12-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_post_user_lat_remove_post_user_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
