# Generated by Django 5.1.2 on 2024-12-16 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visible_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
    ]
