# Generated by Django 5.1.1 on 2024-10-08 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('quickness', models.PositiveIntegerField(help_text='Time in minutes')),
                ('nutrition', models.JSONField()),
                ('restrictions', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy_free', 'Dairy Free'), ('gluten_free', 'Gluten Free'), ('nut_free', 'Nut Free'), ('none', 'None')], default='none', max_length=20)),
                ('allergens', models.CharField(choices=[('nuts', 'Nuts'), ('gluten', 'Gluten'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('shellfish', 'Shellfish'), ('eggs', 'Eggs'), ('none', 'None')], default='none', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(through='ingredients.RecipeIngredient', to='ingredients.ingredient')),
            ],
        ),
    ]
