# Generated by Django 5.1.2 on 2024-12-04 19:14

from django.db import migrations

def preload_allergens_and_restrictions(apps, schema_editor):
    Allergen = apps.get_model('recipes', 'Allergen')
    DietaryRestriction = apps.get_model('recipes', 'DietaryRestriction')

    allergens = [
        "Peanuts",
        "Tree Nuts",
        "Milk",
        "Eggs",
        "Fish",
        "Shellfish",
        "Soy",
        "Wheat",
        "Dairy"
    ]

    restrictions = [
        "Vegetarian",
        "Vegan",
        "Gluten-Free",
        "Keto",
        "Halal",
        "Kosher",
        "Pescatarian",
    ]

    for allergen in allergens:
        Allergen.objects.get_or_create(name=allergen)

    for restriction in restrictions:
        DietaryRestriction.objects.get_or_create(name=restriction)

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_allergen_dietaryrestriction_remove_recipe_rating_and_more'),
    ]

    operations = [
        migrations.RunPython(preload_allergens_and_restrictions),
    ]
