# Generated by Django 5.1.2 on 2024-12-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_add_new_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
