name: Build and deploy Python app and Frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Backend setup
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install backend dependencies
        run: pip install -r requirements.txt

      - name: Collect backend static files
        run: python manage.py collectstatic --noinput 

      # Frontend setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version required by your frontend

      - name: Install frontend dependencies
        run: npm install --prefix frontend/

      - name: Build frontend
        run: npm run build --prefix frontend/

      # Package both backend and frontend
      - name: Package artifacts
        run: |
          zip -r release.zip ./* \
          -x 'venv/*' \
          -x 'frontend/node_modules/*' \
          -x '*.git*'

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: full-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: full-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'campus-cuisine-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2E77... }}
