name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest-django  # Install pytest-django

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: campus_grocery_app.settings
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q  # Run the tests
