
name: Run Tests DB

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest-django  # Install pytest-django

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done
          
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: campus_grocery_app.settings
          DATABASE_URL: postgres://postgres:password@localhost:5432/postgres  # Set the correct DB URL
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q  # Run the tests
